spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
  datasource:
      driverClass: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/temp?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true
      username: root
      password: 123456
  aop:
    proxy-target-class: true
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lunzi.camry.domain
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  redis:
      host: 127.0.0.1
      port: 6379
      #连接池
      max-idle: 100
      min-idle: 0
      max-active: 200
      max-wait-millis: -1
info:
  author:
    realname: lunzi
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
logging:
  level:
    com.lunzi.camry.mapper: debug
server:
  port: 2028
demo:
  user:
    userName: wst
    userAge: 12
example:
  service:
    enabled: true





